### PR TITLE
Fix browser source URL

### PR DESCRIPTION
**Pull request by holiber**

### CODE REVIEW

**Comment by gettinToasty** [comment]
I don't really understand this fix, it seems like you're just moving all of the same stuff to another place and then using that new function?

**Comment by andycreeth** [comment]
It looks like he moved the defaults from a place where they would apply on create/update to a place where they would only apply on create.

**Comment by holiber** [comment]
Exactly

**Comment by andycreeth** [comment]
Confirming this resolves the issue.  Thanks Alex.

**Pull request merged**
