### PR TITLE
custom resolution support

### PR DESCRIPTION
**Pull request by holiber**

### CODE REVIEW

**Comment by eddyStreamlabs** [comment]
Seems to work great : 
 - Upscaling / downscaling works
 - Importing custom resolutions from obs works 

-> Require an update of obs-studio-node.

**Comment by holiber** [comment]
Lets merge it after obs-studio-node will be merged

**Comment by eddyStreamlabs** [comment]
Sounds good

**Comment by holiber** [comment]
Yeah, we are trying to use the `multiselect` like `autocomplete` component. Actually, if we have plans to use that component only for the resoultion selector, I prefer to use the standard `multiselect` with a  `custom` option which can switch the multiselect view to the 2 simple text fields - `width` and `height`

**Comment by holiber** [comment]
@eddyStreamlabs are node-obs changes merged?

**Comment by eddyStreamlabs** [comment]
Should be now.

**Pull request closed without merging**
