### PR TITLE
Add facemask plugin dependency

### PR DESCRIPTION
**Pull request by brankalakic**

### CODE REVIEW

**Comment by gettinToasty** [comment]
@kuhasuki who's in charge of this PR now?

**Comment by kuhasuki** [comment]
@glaba13 this is part of changing the release process for face mask plugin?

**Comment by glaba13** [comment]
@kuhasuki yes, this is the last part left for AppVeyor.

**Comment by andycreeth** [comment]
This is good to go whenever you (FM team) wants to merge it.

**Pull request merged**
