### PR TITLE
refactor: add incremental strict null checks config/scripts

### PR DESCRIPTION
**Pull request by blackxored**
Starting branch. Selectively enable `strictNullChecks` by running custom script on `package.json`.

### CODE REVIEW

**Comment by andycreeth** [comment]
Would it be possible to fail the CI build if the number of errors emitted by `yarn strict-null-check` is increased by the PR?

**Comment by andycreeth** [comment]
Oh I just noticed you're only compiling individual files.  Got it.

**Comment by andycreeth** [comment]
In that case we should fail CI if it emits any errors at all.

**Comment by andycreeth** [comment]
What's the status on this?

**Comment by blackxored** [comment]
Let's discuss this one next week.

**Comment by andycreeth** [comment]
Per our discussion last week I think we should add this to our CI build and merge.

**Pull request closed without merging**
