### PR TITLE
fix widget themes notification

### PR DESCRIPTION
**Pull request by kuhasuki**
Didn't know where to put the function so I added it to notification service.

### CODE REVIEW

**Comment by gettinToasty** [comment]
hmm this seems like kinda a weird/funky place to me, why not just get the magic link service directly in the notification?

**Comment by kuhasuki** [comment]
> hmm this seems like kinda a weird/funky place to me, why not just get the magic link service directly in the notification?

Magic link service only return the url. I'm not sure what I can/ can't do in the action property of a notification. The typedef says it must be  IJsonRpcRequest. Agree that notification service might not be the best place, happy to consider other services that logically make more sense. None come to mind for me right away.

**Comment by gettinToasty** [comment]
what i mean is adding `openWidgetThemesMagicLink` to `magicLinksService` and doing this
```
this.jsonrpcService.createRequest(
  Service.getResourceId(this.magicLinksService),
  'openWidgetThemesMagicLink',
)
```

**Comment by kuhasuki** [comment]
> what i mean is adding `openWidgetThemesMagicLink` to `magicLinksService` and doing this
> 
> ```
> this.jsonrpcService.createRequest(
>   Service.getResourceId(this.magicLinksService),
>   'openWidgetThemesMagicLink',
> )
> ```

Yeah I think that would be fine. Will move the function to magic link service

**Pull request merged**
