### PR TITLE
Api documentation

### PR DESCRIPTION
**Pull request by holiber**
All API endpoints have to be described in files with name `myservicename-api.ts`

### CODE REVIEW

**Comment by andycreeth** [comment]
image
These links don't seem to work for me.

**Comment by andycreeth** [comment]
I'm going to push a commit with all of the English grammar corrections.

Also, were you ever able to figure out how to change the title from `slobs-client` to `streamlabs-obs` without modifying the `package.json` name?

**Comment by holiber** [comment]
I added 'AppService.setArgv()'. Now API settings will be shown if application starts with `--adv-settings` option

**Comment by holiber** [comment]
Looks like the tests fails because of the client requires another version of `obs-studio-node`

**Comment by holiber** [comment]
my local test passed

**Comment by holiber** [comment]
@andycreeth I've removed compiled docs

**Comment by andycreeth** [comment]
Cool, this is good to merge. 🎉

**Pull request merged**
