### PR TITLE
Test widgets improvement

### PR DESCRIPTION
**Pull request by mbiemiller**
- fix for test widgets so it doesn't get cut off from preview on live page

### CODE REVIEW

**Comment by andycreeth** [comment]
Thanks for fixing this.  I'm notification as I use this that it feels like it should dismiss itself once I've chosen a widget to test.  Otherwise it has a tendency to just stick around and block important UI (like you notifications area).  What do you think?

**Comment by mbiemiller** [comment]
I don't think we should close on click. People usually have a different variation for every event type so they test them all. I do however think we should automatically close it if you change pages or go live.

**Comment by andycreeth** [comment]
Cool that sounds like a good solution to me.

**Comment by andycreeth** [comment]
We can circle back and add that, since it's a little complicated.  Going to merge this for now.

**Pull request merged**
