### PR TITLE
dynamic notifications

### PR DESCRIPTION
**Pull request by andycreeth**
It's a little weird, but I think this is going to be the most reliable solution for notifications.  Basically the solution involves allowing the notifications area to grow/shrink to take up all the remaining space in the footer.  Then, the notifications area is constantly checking the size of itself, and hides the full text of the notification if the area it occupies is too small.

### CODE REVIEW

**Comment by holiber** [comment]
It's better to use the event-based ResizeSensor from http://marcj.github.io/css-element-queries/ for observing elements size without creating additional `setInterval` cycles

**Comment by andycreeth** [comment]
Hmm.  I would love to know what that library is doing under the hood.  There's no such thing as a resize event on an element.

**Comment by andycreeth** [comment]
This library looks interesting, but it seems high risk to add right now.  I'm going to investigate it later.  There are a few different places this would be really useful to us.

**Comment by holiber** [comment]
I used on some projects. It attaches an additional element to you element and check it's size with some magic on requestAnimationFrame. I don't remember exactly how, but fortunately the code of ResizeSensor is not big to investigate.

**Pull request merged**
