### PR TITLE
Regression testing screenshots

### PR DESCRIPTION
**Pull request by holiber**
to run screen tests:
- make and commit any changes in you branch that affects html rendering
- run `yarn screentest`
- open `test-dist/screentest/preview.html` for results

I'm going to figure out an Appveyor integration in the next PR

### CODE REVIEW

**Comment by andycreeth** [comment]
This branch looks like it has your changes to the live dock in it.  We ended up closing that PR.  Can you maybe remove those changes from this PR?

**Comment by holiber** [comment]
@andycreeth I added a possibility to show/hide lifedoc in `CustomizationService` because I need this feature to make screenshots with a different lifedock state. However I realized that I have to authorize some user in screen-tests for that. So I decided to do that in some another next PR to avoid big changes, and I'm going to use this code from `CustomizationService`

**Comment by holiber** [comment]
I'm going to create more screentests when the all environment will be ready

**Comment by andycreeth** [comment]
It's called the LiveDock, not the LifeDock.

**Comment by holiber** [comment]
Ouch

**Comment by holiber** [comment]
Could we merge it, to continue with appveyor integration?

**Comment by andycreeth** [comment]
Yup this is good to merge.

**Comment by holiber** [comment]
to run screen tests:

make and commit any changes in you branch that affects html rendering
run yarn screentest
open test-dist/screentest/preview.html for results

**Pull request merged**
