### PR TITLE
adds supporter goals, changes routes for donation goals, removes post…

### PR DESCRIPTION
**Pull request by karljakober**
… end goal

### CODE REVIEW

**Comment by andycreeth** [comment]
Ok so per conversation in slack this code has even been run.  @gettinToasty When you have a free moment can you take this over and test / make sure it's good to go?

**Comment by gettinToasty** [comment]
@andycreeth yea im just not sure how to pull from a fork haha

**Comment by andycreeth** [comment]
Next to the merge button below, click "command line instructions" and it will tell you how to pull from his fork onto a branch in our repo.

**Comment by gettinToasty** [comment]
@karljakober just tried this out and getting a 405 when i try to load FB goals, beta may have changed since this was put on it or something but if not it's gonna need fixin'

**Comment by andycreeth** [comment]
Any update on this?  Still broken on the server side?

**Comment by kuhasuki** [comment]
This functionality was merged in https://github.com/stream-labs/streamlabs-obs/pull/1919

**Pull request closed without merging**
