### PR TITLE
use local scale to make autofit in auto gamecapture mode

### PR DESCRIPTION
**Pull request by summeroff**
required osn PR https://github.com/stream-labs/obs-studio-node/pull/608

### CODE REVIEW

**Comment by gettinToasty** [comment]
this looks like it turns on autofit for every game capture?

**Comment by summeroff** [comment]
kind of. it will be handled inside obs code transparently for upper levels. 
it is not implement autofit it is also gonna keep fixed scale between games( which can have different window size ). 
so workaround with disabling autofit after user manually resize no more required.

**Comment by gettinToasty** [comment]
@summeroff are the BE changes in for this?

**Comment by summeroff** [comment]
not yet https://github.com/stream-labs/obs-studio-node/pull/608

**Comment by andycreeth** [comment]
@summeroff Please go ahead and merge this into staging whenever the backend is updated.

**Comment by EddyGharbi** [comment]
Will merge once OSN update is in

**Pull request merged**
