### PR TITLE
chore(onboarding): use generic msg as we support more services #trivial

### PR DESCRIPTION
**Pull request by blackxored**
Replaces the "Sign in with Twitch or Youtube account" with "Sign in with your service account".
Translations other than English would need updating.

### CODE REVIEW

**Comment by andycreeth** [comment]
Good catch.  I think we should replace "service account" with "streaming account".  I think that would be more in the vernacular.

**Comment by andycreeth** [comment]
Also, is this the right way to handle it?  I think you just want to modify the key in the `en-US` file.  The key will be missing in all other files, so our translation system will recognize it as a new string to be translated.  By changing the key in all files, it will not be flagged as a string that needs translation.  CC: @holiber is that correct?

**Comment by holiber** [comment]
That's correct. We store our translations in Crowdin. All files except en-Us folder are auto-generated.

**Comment by blackxored** [comment]
Changed to "streaming". Is there any action required from me on this one, assuming we don't want to stick to old keys?

**Comment by blackxored** [comment]
@gettinToasty I believe so, yes. @holiber, can you confirm?

**Comment by andycreeth** [comment]
Yes to be clear @blackxored what you should do is:
- Add new key to `en-US`
- Remove old key from `en-US`
- DO NOT touch any other language JSON files.

**Comment by andycreeth** [comment]
Aaaaand I just checked the diff and that's exactly what you did already :)  We can merge this.

**Pull request merged**
